#功能:
#>类型
#################################
#####       语言文件        #####
#################################
#可以使用相对路径(是相对于服务端所在文件夹的路径)
language: "plugins/Lib_types/language_cn.yml"
#################################
#####         描述          #####
#################################
description:
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
per: "lib.types"             #类型管理权限