#功能:
#>类型
#################################
#####       语言文件        #####
#################################
lang:
  default: "cn"                #默认语言(指不明确指定语言的情况下)
  error: "en"                  #错误时使用语言(指指定的语言配置不存在时使用的语言配置)
#################################
#####         描述          #####
#################################
description:
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
per: "lib.types.admin"        #类型管理权限